package com.lyht.business.info.dao;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.lyht.business.info.entity.InfoOwnerEntity;
import com.lyht.business.info.vo.InfoMoveAggregateCardVO;
import com.lyht.business.info.vo.InfoMoveAggregateVO;

public interface InfoMoveAggregateDao extends JpaRepository<InfoOwnerEntity, Integer> {

	/**
	 * 搬迁安置汇总--按行政区
	 * 
	 * @param mergaerName
	 * @return
	 */
	@Query(value = "SELECT" 
			+ " pr.city_code AS cityCode," 
			+ " pr.parent_code AS parentCode,"
			+ " pr.merger_name AS mergerName," 
			+ " pr.name AS name," 
			+ " pr.level_type AS level,"
			+ " ( SELECT SUM(tioi.immigrant) FROM t_info_owner tioi WHERE tioi.region = pr.city_code) AS households,"
			+ " ( SELECT SUM(tifi.i_population) FROM t_info_owner tifi WHERE tifi.region = pr.city_code) AS population,"
			+ " ( SELECT SUM(tioi.immigrant) FROM t_info_owner tioi WHERE tioi.region = pr.city_code AND tioi.scope IN('D8D5AAD9DC','E78D14E7BE','D18482159A')) AS pivotTotalHouseholds,"
			+ " ( SELECT SUM(tifi.i_population) FROM t_info_owner tifi WHERE tifi.region = pr.city_code AND tifi.scope IN('D8D5AAD9DC','E78D14E7BE','D18482159A')) AS pivotTotalPopulation,"
			+ " ( SELECT SUM(tioi.immigrant) FROM t_info_owner tioi WHERE tioi.region = pr.city_code AND tioi.scope IN('CE81C0FA94','24ACBF9107')) AS reservoirTotalHouseholds,"
			+ " ( SELECT SUM(tifi.i_population) FROM t_info_owner tifi WHERE tifi.region = pr.city_code AND tifi.scope IN('CE81C0FA94','24ACBF9107')) AS reservoirTotalPopulation,"
			+ " ( SELECT SUM(tioi.immigrant) FROM t_info_owner tioi WHERE tioi.region = pr.city_code AND tioi.scope = '348F5B68BA') AS newTownHouseholds,"
			+ " ( SELECT SUM(tifi.i_population) FROM t_info_owner tifi WHERE tifi.region = pr.city_code AND tifi.scope = '348F5B68BA') AS newTownPopulation"
			+ " FROM pub_region pr" 
			+ " WHERE pr.merger_name LIKE CONCAT('云南省,迪庆藏族自治州,维西傈僳族自治县','%')", nativeQuery = true)
	List<InfoMoveAggregateVO> findMoveAggregate();
	
	/**
	 * 搬迁安置--汇总卡片
	 * 
	 * @return
	 */
	@Query(value = "SELECT" 
			+ " : AS serialNumber," 
			+ " '集中安置' AS placeMethod," 
			+ " NULL AS placeType,"
			+ " NULL AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_type IN('5866417EC7','E0AD4AB501')"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_type IN('5866417EC7','E0AD4AB501')"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '1.1' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " '农村集中安置' AS placeType," 
			+ " NULL AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_type = '5866417EC7'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_type = '5866417EC7'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '1.1.1' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " NULL AS placeType," 
			+ " '兰永' AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_name LIKE '%兰永%'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_name LIKE '%兰永%'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '1.1.2' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " NULL AS placeType," 
			+ " '苍浦底' AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_name LIKE '%苍浦底%'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_name LIKE '%苍浦底%'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '1.1.3' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " NULL AS placeType," 
			+ " '杵打' AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_name LIKE '%杵打%'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_name LIKE '%杵打%'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '1.1.4' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " NULL AS placeType," 
			+ " '窝怒' AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_name LIKE '%窝怒%'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_name LIKE '%窝怒%'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '1.1.5' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " NULL AS placeType," 
			+ " '洛吉古' AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_name LIKE '%洛吉古%'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_name LIKE '%洛吉古%'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '1.1.6' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " NULL AS placeType," 
			+ " '小谷田' AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_name LIKE '%小谷田%'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_name LIKE '%小谷田%'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '1.1.7' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " NULL AS placeType," 
			+ " '阿米俄' AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_name LIKE '%阿米俄%'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_name LIKE '%阿米俄%'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '1.1.8' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " NULL AS placeType," 
			+ " '白浪统' AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_name LIKE '%白浪统%'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_name LIKE '%白浪统%'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '1.2' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " '集镇集中安置' AS placeType," 
			+ " NULL AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_type = 'E0AD4AB501'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_type = 'E0AD4AB501'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '1.2.1' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " NULL AS placeType," 
			+ " '白济汛' AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_name LIKE '%白济汛%'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_name LIKE '%白济汛%'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '1.2.2' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " NULL AS placeType," 
			+ " '康普' AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_name LIKE '%康普%'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_name LIKE '%康普%'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '2' AS serialNumber," 
			+ " '分散安置' AS placeMethod," 
			+ " NULL AS placeType," 
			+ " NULL AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_type IN('2E8EDB1C69','C7B441FEE9')"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_type IN('2E8EDB1C69','C7B441FEE9')"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '2.1' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " '分散后靠' AS placeType," 
			+ " NULL AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_type = '2E8EDB1C69'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_type = '2E8EDB1C69'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '2.2' AS serialNumber," 
			+ " NULL AS placeMethod," 
			+ " '分散货币' AS placeType," 
			+ " NULL AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND tioi.place_type = 'C7B441FEE9'"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND tifi.place_type = 'C7B441FEE9'"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)"
			+ " UNION ALL" 
			+ " SELECT"
			+ " '3' AS serialNumber," 
			+ " '其他' AS placeMethod," 
			+ " NULL AS placeType," 
			+ " NULL AS placeName,"
			+ " SUM(("
			+ "  SELECT SUM(tioi.immigrant) FROM t_info_owner tioi"
			+ " WHERE tioi.region = pr.city_code AND (tioi.place_type IS NULL OR tioi.place_type NOT IN('5866417EC7','E0AD4AB501','2E8EDB1C69','C7B441FEE9'))"
			+ " AND IF(:isAll = false, tioi.scope IN(:scopes), 1=1)"
			+ " )) AS households,"
			+ " SUM(("
			+ "  SELECT SUM(tifi.i_population) FROM t_info_owner tifi"
			+ " WHERE tifi.region = pr.city_code AND (tifi.place_type IS NULL OR tifi.place_type NOT IN('5866417EC7','E0AD4AB501','2E8EDB1C69','C7B441FEE9'))"
			+ " AND IF(:isAll = false, tifi.scope IN(:scopes), 1=1)"
			+ " )) AS population"
			+ " FROM pub_region pr" 
			+ " WHERE 1 = 1"
			+ " AND IF(:mergerName IS NOT NULL AND :mergerName != '', pr.merger_name LIKE CONCAT(:mergerName,'%'), 1 = 1)", nativeQuery = true)
	List<InfoMoveAggregateCardVO> findMoveAggregateCard(@Param("mergerName") String mergerName, @Param("scopes") List<String> scopes, @Param("isAll") boolean isAll);



	@Modifying
	@Query(value = "INSERT INTO `t_info_statistical_relocation_population` (`name`, `cityCode`, " +
			"`parentCode`, `households`, `population`, `reservoirTotalHouseholds`, `reservoirTotalPopulation`, " +
			"`pivotTotalHouseholds`, `pivotTotalPopulation`, `pivotTotalHouseholds2`, `pivotTotalPopulation2`, " +
			"`newTownHouseholds`, `newTownPopulation`, `householdsProgramme`, `populationProgramme`, " +
			"`reservoirTotalHouseholdsProgramme`, `reservoirTotalPopulationProgramme`, " +
			"`pivotTotalHouseholdsProgramme`, `pivotTotalPopulationProgramme`, `pivotTotalHouseholdsProgramme2`, " +
			"`pivotTotalPopulationProgramme2`, `newTownHouseholdsProgramme`, `newTownPopulationProgramme`) VALUES " +
			"(:name, :cityCode, :parentCode, :households, :population, :reservoirTotalHouseholds, :reservoirTotalPopulation, :pivotTotalHouseholds," +
			" :pivotTotalPopulation, :pivotTotalHouseholds2, :pivotTotalPopulation2, :newTownHouseholds, :newTownPopulation" +
			", :householdsProgramme, :populationProgramme, :reservoirTotalHouseholdsProgramme, :reservoirTotalPopulationProgramme, " +
			":pivotTotalHouseholdsProgramme, :pivotTotalPopulationProgramme, :pivotTotalHouseholdsProgramme2, :pivotTotalPopulationProgramme2," +
			" :newTownHouseholdsProgramme, :newTownPopulationProgramme);", nativeQuery = true)
	void insertInfo(@Param("name") String name, @Param("cityCode") String cityCode, @Param("parentCode") String parentCode
			, @Param("households") String households, @Param("population") String population, @Param(
					"reservoirTotalHouseholds") String reservoirTotalHouseholds, @Param("reservoirTotalPopulation") String reservoirTotalPopulation, @Param("pivotTotalHouseholds") String pivotTotalHouseholds
			, @Param("pivotTotalPopulation") String pivotTotalPopulation, @Param("pivotTotalHouseholds2") String pivotTotalHouseholds2, @Param("pivotTotalPopulation2") String pivotTotalPopulation2,
					@Param("newTownHouseholds") String newTownHouseholds, @Param("populationProgramme") String populationProgramme
			, @Param("householdsProgramme") String householdsProgramme, @Param("reservoirTotalHouseholdsProgramme") String reservoirTotalHouseholdsProgramme, @Param("newTownPopulation") String newTownPopulation,
					@Param("reservoirTotalPopulationProgramme") String reservoirTotalPopulationProgramme, @Param("pivotTotalHouseholdsProgramme") String pivotTotalHouseholdsProgramme
			, @Param("pivotTotalPopulationProgramme") String pivotTotalPopulationProgramme, @Param("pivotTotalHouseholdsProgramme2") String pivotTotalHouseholdsProgramme2, @Param("pivotTotalPopulationProgramme2") String pivotTotalPopulationProgramme2,
					@Param("newTownHouseholdsProgramme") String newTownHouseholdsProgramme, @Param("newTownPopulationProgramme") String newTownPopulationProgramme);
}